[package]
name = "verbump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
gumdrop = "0.8.1"
semver = "1.0.9"
